/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AuthActionRouteImport } from './routes/auth-action'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesVeterinaryRouteImport } from './routes/industries/veterinary'
import { Route as IndustriesSalonsWellnessRouteImport } from './routes/industries/salons-wellness'
import { Route as IndustriesRealEstateRouteImport } from './routes/industries/real-estate'
import { Route as IndustriesItServicesRouteImport } from './routes/industries/it-services'
import { Route as IndustriesHotelsHospitalityRouteImport } from './routes/industries/hotels-hospitality'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries/healthcare'
import { Route as IndustriesEducationRouteImport } from './routes/industries/education'
import { Route as IndustriesDentalRouteImport } from './routes/industries/dental'
import { Route as IndustriesCosmeticClinicsRouteImport } from './routes/industries/cosmetic-clinics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/auth-action',
  path: '/auth-action',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesVeterinaryRoute = IndustriesVeterinaryRouteImport.update({
  id: '/industries/veterinary',
  path: '/industries/veterinary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSalonsWellnessRoute =
  IndustriesSalonsWellnessRouteImport.update({
    id: '/industries/salons-wellness',
    path: '/industries/salons-wellness',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRealEstateRoute = IndustriesRealEstateRouteImport.update({
  id: '/industries/real-estate',
  path: '/industries/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesItServicesRoute = IndustriesItServicesRouteImport.update({
  id: '/industries/it-services',
  path: '/industries/it-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHotelsHospitalityRoute =
  IndustriesHotelsHospitalityRouteImport.update({
    id: '/industries/hotels-hospitality',
    path: '/industries/hotels-hospitality',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesEducationRoute = IndustriesEducationRouteImport.update({
  id: '/industries/education',
  path: '/industries/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesDentalRoute = IndustriesDentalRouteImport.update({
  id: '/industries/dental',
  path: '/industries/dental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesCosmeticClinicsRoute =
  IndustriesCosmeticClinicsRouteImport.update({
    id: '/industries/cosmetic-clinics',
    path: '/industries/cosmetic-clinics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-action': typeof AuthActionRoute
  '/book-demo': typeof BookDemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/industries/cosmetic-clinics': typeof IndustriesCosmeticClinicsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hotels-hospitality': typeof IndustriesHotelsHospitalityRoute
  '/industries/it-services': typeof IndustriesItServicesRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/industries/salons-wellness': typeof IndustriesSalonsWellnessRoute
  '/industries/veterinary': typeof IndustriesVeterinaryRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-action': typeof AuthActionRoute
  '/book-demo': typeof BookDemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/industries/cosmetic-clinics': typeof IndustriesCosmeticClinicsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hotels-hospitality': typeof IndustriesHotelsHospitalityRoute
  '/industries/it-services': typeof IndustriesItServicesRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/industries/salons-wellness': typeof IndustriesSalonsWellnessRoute
  '/industries/veterinary': typeof IndustriesVeterinaryRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-action': typeof AuthActionRoute
  '/book-demo': typeof BookDemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/industries/cosmetic-clinics': typeof IndustriesCosmeticClinicsRoute
  '/industries/dental': typeof IndustriesDentalRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/hotels-hospitality': typeof IndustriesHotelsHospitalityRoute
  '/industries/it-services': typeof IndustriesItServicesRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/industries/salons-wellness': typeof IndustriesSalonsWellnessRoute
  '/industries/veterinary': typeof IndustriesVeterinaryRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-action'
    | '/book-demo'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/industries/cosmetic-clinics'
    | '/industries/dental'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hotels-hospitality'
    | '/industries/it-services'
    | '/industries/real-estate'
    | '/industries/salons-wellness'
    | '/industries/veterinary'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-action'
    | '/book-demo'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/industries/cosmetic-clinics'
    | '/industries/dental'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hotels-hospitality'
    | '/industries/it-services'
    | '/industries/real-estate'
    | '/industries/salons-wellness'
    | '/industries/veterinary'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/auth-action'
    | '/book-demo'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/industries/cosmetic-clinics'
    | '/industries/dental'
    | '/industries/education'
    | '/industries/healthcare'
    | '/industries/hotels-hospitality'
    | '/industries/it-services'
    | '/industries/real-estate'
    | '/industries/salons-wellness'
    | '/industries/veterinary'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthActionRoute: typeof AuthActionRoute
  BookDemoRoute: typeof BookDemoRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  IndustriesCosmeticClinicsRoute: typeof IndustriesCosmeticClinicsRoute
  IndustriesDentalRoute: typeof IndustriesDentalRoute
  IndustriesEducationRoute: typeof IndustriesEducationRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesHotelsHospitalityRoute: typeof IndustriesHotelsHospitalityRoute
  IndustriesItServicesRoute: typeof IndustriesItServicesRoute
  IndustriesRealEstateRoute: typeof IndustriesRealEstateRoute
  IndustriesSalonsWellnessRoute: typeof IndustriesSalonsWellnessRoute
  IndustriesVeterinaryRoute: typeof IndustriesVeterinaryRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-action': {
      id: '/auth-action'
      path: '/auth-action'
      fullPath: '/auth-action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/veterinary': {
      id: '/industries/veterinary'
      path: '/industries/veterinary'
      fullPath: '/industries/veterinary'
      preLoaderRoute: typeof IndustriesVeterinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/salons-wellness': {
      id: '/industries/salons-wellness'
      path: '/industries/salons-wellness'
      fullPath: '/industries/salons-wellness'
      preLoaderRoute: typeof IndustriesSalonsWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/real-estate': {
      id: '/industries/real-estate'
      path: '/industries/real-estate'
      fullPath: '/industries/real-estate'
      preLoaderRoute: typeof IndustriesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/it-services': {
      id: '/industries/it-services'
      path: '/industries/it-services'
      fullPath: '/industries/it-services'
      preLoaderRoute: typeof IndustriesItServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/hotels-hospitality': {
      id: '/industries/hotels-hospitality'
      path: '/industries/hotels-hospitality'
      fullPath: '/industries/hotels-hospitality'
      preLoaderRoute: typeof IndustriesHotelsHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/education': {
      id: '/industries/education'
      path: '/industries/education'
      fullPath: '/industries/education'
      preLoaderRoute: typeof IndustriesEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/dental': {
      id: '/industries/dental'
      path: '/industries/dental'
      fullPath: '/industries/dental'
      preLoaderRoute: typeof IndustriesDentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/cosmetic-clinics': {
      id: '/industries/cosmetic-clinics'
      path: '/industries/cosmetic-clinics'
      fullPath: '/industries/cosmetic-clinics'
      preLoaderRoute: typeof IndustriesCosmeticClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthActionRoute: AuthActionRoute,
  BookDemoRoute: BookDemoRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  IndustriesCosmeticClinicsRoute: IndustriesCosmeticClinicsRoute,
  IndustriesDentalRoute: IndustriesDentalRoute,
  IndustriesEducationRoute: IndustriesEducationRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesHotelsHospitalityRoute: IndustriesHotelsHospitalityRoute,
  IndustriesItServicesRoute: IndustriesItServicesRoute,
  IndustriesRealEstateRoute: IndustriesRealEstateRoute,
  IndustriesSalonsWellnessRoute: IndustriesSalonsWellnessRoute,
  IndustriesVeterinaryRoute: IndustriesVeterinaryRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
